### ISSUE TITLE
Cape Priority Toggle

### ISSUE THREAD

**Issue by ZenIsBestWolf** [hibiii/Kappa#11]
For some reason #10 was closed without any warning from the OP. I see issue #7 but I still think the option should exist.

Currently Kappa prioritizes official Mojang capes over OptiFine, which does not reflect native OptiFine behavior.

However, this behavior is certainly desirable for some users. This is a request for a toggle, with the default being OptiFine > Mojang, in order to parody OptiFine correctly.

However if the goals of this mod is to truly be a "no-frills" type deal, perhaps simply parodying OptiFine's behavior would be better than adding a toggle.

**Comment by hibiii** [comment]
wai + wontfix + migration cape user detected

Mojang capes are prioritized because they're official capes. This is a Minecraft mod, not an OptiFine mod.

If you want me to go into detail, then there are three reasons why I'm keeping it this way:

1. By prioritizing Mojang capes, I can claim that I'm more on the side of Mojang should they get angry with lawyers, but this is only a minor point. I will comply with a C&D should I get sent one, but maybe perhaps it should be OptiFine worrying about it more than me.
2. It is easier to just check if a game profile has a cape texture and store the OptiFine cape there than it is to keep a map of game profiles per cape textures, and adding hooks to clear that map to prevent leaking memory, and preventing the official cape from rendering, etc. Kappa is very barebones, and that's what allows for a single binary to work with *multiple* Minecraft snapshots sometimes multiple releases even. The current code injection points are unusually stable compared to the rest of the game, but the necessary code to make OptiFine priority over Mojang work would increase the surface area of Kappa for breakages across versions.
3. I sincerely believe that capes should be customizable and available to general public via *official* means *including "rare" and one-of-a-kind capes*. The rarity and exclusivity of anything digital only fuels a cesspool of toxic behavior, be it Minecraft capes, usernames, Twitter handles, Discord usernames, etc. Mojang's "solution" of migration and bedrock pre-owning capes is just a techbro nonsolution, they only serve to maintain the status quo.

Also, a toggle would require configuration, thus requiring a configuration screen, and a way to activate said screen. Also also, since we're talking injection points, changing the priority would require the user to restart the entire game, which can be outrageously annoying to do if the user is playing on a particularly large modpack. Avoiding this by adding runtime checks would not only marginally slow down the client (more than TLS would a CDN, btw), but also likely lead to undefined behavior, which is fixed by restarting the client. The only good solution would to enforce OptiFine cape priority over Mojang without configuration.

I don't wish to emulate OptiFine's behavior, I want a small and clean way to add Minecaft capes to snapshots. These are all reasons I've talked about in public channels before. If I wanted to emulate OptiFine's behavior but better, I'd contribute to Sodium, Starlight, and even Iris. This is _my_ mod, and I think that saying "no" every few months to people asking for priority or why Kappa isn't working is a better use of my time compared to thoroughly testing a much larger code base prone to edge cases every single wednesday when snapshots are coming out. Not to mention, the toxic background of Minecraft modding, like yourself, where people order you to add stuff instead of politely asking why something is the case, *specially* if the mod has detailed documentation .

**Comment by ZenIsBestWolf** [comment]
I'm not deeply familiar with the implementation of something like this, hence why I didn't just do it and then open a PR.

I didn't think it would be so much trouble, sorry.

It was just a polite request, not a demand. I'm sorry if it came across aggressive.
