### ISSUE TITLE
Kappa not working? or im just dumb.

### ISSUE THREAD

**Issue by Imabanana80** [hibiii/Kappa#8]
does my migrator cape need to be off for it to work? Am i not doing something right? Do i need to configure something or does it work right out of the box?

![image](https://user-images.githubusercontent.com/85228043/235452064-1bcc01e1-35db-4155-a1d0-abf017a15e7e.png)

**Comment by hibiii** [comment]
Kappa prioritizes the vanilla cape over OptiFine, partially because vanilla capes are official and OptiFine capes are not. You need to disable your migrator cape if you'd like to view your OptiFine cape with Kappa.

And, Kappa has no configuration, it shows OF capes for players with them and without vanilla ones by default.

**Comment by Imabanana80** [comment]
Is it possible to edit the code to prioritize optifine capes?

**Comment by hibiii** [comment]
I don't want to.

OptiFine capes go very clearly against the Commercial Usage Guidelines, and Mojang has taken action with it. I personally consider Kappa to be in the gray area because it doesn't have paid capes itself, but changing this one thing would inch it ever so slightly closer into the wrong.

For more information, this was originally an implementation quirk that came to be by reusing existing fields to store references to capes, but my stance has since changed into accepting that as intended behavior. For even more information on the technical side, see <https://hibiscus.pet/mods/kappa/documentation>.

**Comment by Imabanana80** [comment]
Ohhh. I never knew mojang actually took action against optifine capes.

**Comment by hibiii** [comment]
I haven't heard of them taking action over paid capes but them blocking pay-to-win servers back in 2014 set a precedent.

**Comment by Imabanana80** [comment]
oh. nice to know. Another question, is there a quick way for me to reload my optifine cape while using the mod?. I tried f3+t and turning the cape off and on.

**Comment by hibiii** [comment]
Only restarting your client.

**Comment by Imabanana80** [comment]
oh rip
